services:

  postgres:
    image: postgres:${TAG_VERSION}
    
    ports:
      - "${DB_PORT}:${DB_PORT}"

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}

  

